.TH man 6 "21 nov 2020" "??" "sudoku_cpp man page"
.SH NAME
sudoku \- solve a sudoku puzzle
.SH SYNOPSIS
sudoku [options] [-f file] [grid]
.SH DESCRIPTION
sudoku is a sudoku solver
.SH OPTIONS
  -f filename: read grid from human readable file. If not given, then you need to provide the grid on the command-line as one 81 character long string, with '.' for unknow cells.
  -l: will log all the steps (eliminating a candidate in a cell)
  -v: verbose, will print out the mains steps and algorithms used. You'd better redirect in a file with that one, lots of output. Implies option "-s".
  -s: will save the grid to a file name `current.sud` and to a timestamped file (useful when entering grid from command-line)
.SH RETURN VALUE
 0: success (solved puzzle)
 1: unable to read given filename (missing or format error)
 2: missing filename after -f
 3: invalid grid given (must be 81 characters, only digits or '.')
 4: invalid grid
 5: unable to solve
.SH BUGS
No known bugs.
.SH AUTHOR
Sebastien Kramm
Home page: https://github.com/skramm/sudoku_cpp
